import ImageWithFallback from "@/components/image-with-fallback";
import Link from "next/link";
import MoreTeaser from "@/components/more-teaser";
import PageIntro from "@/components/page-intro";
import Script from "next/script";

export const metadata = {
  title: "Projects — Prayag Nepal | Ecommerce & Web Development Nepal",
  description: "Real websites built for real Nepali businesses — ecommerce stores, medical platforms, restaurant sites and more. See the work.",
  keywords: ["ecommerce website Nepal", "website design Nepal", "web developer Nepal", "freelance web developer Nepal"],
  alternates: { canonical: "/projects" }
};
const freelanceProjects = [{ name: "Homa Nepal", slug: "homa-nepal", image: "/gallery/clients/homa.svg", location: "Nepal", industry: "Ecommerce / retail", work: "Full ecommerce website", built: "A complete ecommerce website for Homa Nepal, part of Hokkaido Group.", url: "https://homanepal.com", status: "Live" }, { name: "Surgical Mart Nepal", slug: "surgical-mart-nepal", image: "/gallery/clients/surgical mart.png", location: "Tripureshwor, Nepal", industry: "Medical supplies / ecommerce", work: "Ecommerce website", built: "Built and assisted with an ecommerce platform for surgical supplies.", url: "https://www.surgicalmartnepal.com/", status: "Live" }, { name: "Coffee Dhara", slug: "coffee-dhara", image: "/gallery/clients/coffee dhara.png", location: "Putalisadak, Nepal", industry: "Hospitality / education", work: "Introductory website", built: "An introductory website for a coffee shop and barista school.", url: "https://coffeedhara.netlify.app/", status: "Live" }, { name: "Hokkaido Group", slug: "hokkaido-group", image: "/gallery/clients/Hokkaido Group.jpg", location: "Nepal", industry: "Group company / multiple verticals", work: "Digital presence and website", built: "Collaborating on the group’s wider digital presence and complete website.", status: "In progress" }, { name: "Hokkaido Dekkaido", slug: "hokkaido-dekkaido", image: "/gallery/clients/hokkaido dekkaido.jpg", location: "Nepal", industry: "Group company / multiple verticals", work: "Digital presence and website", built: "Creating the website and digital presence for Hokkaido Group’s sister brand.", status: "In progress" }, { name: "Raag IFC", slug: "raag-ifc", image: "/gallery/clients/raagifc.avif", location: "United States", industry: "Restaurant / food and beverage", work: "Graphics and digital presence", built: "Helped an Indian fusion kitchen kick off its business with graphics and a complete digital presence.", url: "https://www.google.com/maps/place/Raag+Indian+Fusion+Cuisine/@38.6210173,-121.2685832,17z", status: "Live" }];
const workExperience = [{ name: "Procare Nepal", slug: "procare-nepal", image: "/gallery/clients/procare.jpeg", location: "Nepal", industry: "Healthcare / medtech", work: "Frontend development and business development", built: "Assisted frontend development on the existing medical appointment platform and conducted meetings with doctors.", url: "https://www.procarenepal.com/", status: "Live" }, { name: "Nepal Telecom", slug: "nepal-telecom", image: "/gallery/clients/Nepal_Telecom_logo.jpg", location: "Nepal", industry: "Telecommunications", work: "Intern", built: "Internship completed during the second year of college.", status: "Internship" }, { name: "Horeca Suppliers", slug: "horeca-suppliers", mark: "H", location: "Nepal", industry: "Hospitality supply", work: "Graphic designer", built: "Graphic designer role during the first summer break.", status: "Past role" }];
const projectSchema = {"@context":"https://schema.org","@type":"ItemList","name":"Web Development Projects by Prayag Nepal","itemListElement":[{"@type":"CreativeWork","position":1,"name":"Homa Nepal","description":"Ecommerce website for Homa Nepal","url":"https://homanepal.com"},{"@type":"CreativeWork","position":2,"name":"Surgical Mart Nepal","description":"Ecommerce website for surgical supplies","url":"https://surgicalmartnepal.com"},{"@type":"CreativeWork","position":3,"name":"Coffee Dhara","description":"Website for coffee shop and barista school","url":"https://coffeedhara.netlify.app"},{"@type":"CreativeWork","position":4,"name":"Procare Nepal","description":"Medical appointment platform","url":"https://procarenepal.com"}]};
const personalProjects = [{ name: "Garmin AI Insight Guide", description: "Connects your Garmin device to AI and generates useful training insights from your actual workout data. Built for personal use, available for anyone who trains with Garmin.", tags: ["AI", "Fitness Tech", "Personal Tool"], url: "https://garmin-insight-guide.lovable.app/" }, { name: "Udharo Guru", description: "A completed finance management tool built for Nepali local businesses and individuals. It handles expense tracking, expense sharing between individuals, and financial visibility for small businesses — in a way that fits how money actually moves in Nepal.", tags: ["Fintech", "Nepal", "Local Business"], status: "Completed · private build" }];
function ProjectCard({ project }) { return <article className="work-card"><div className="work-logo">{project.mark ? <span className="work-monogram" aria-label={`${project.name} mark`}>{project.mark}</span> : <ImageWithFallback src={project.image || `/gallery/clients/${project.slug}.png`} fallback="/gallery/clients/placeholder.svg" fallbackText={project.name} alt={`${project.name} logo`} width={300} height={150} />}</div><div className="work-primary"><div className="work-title-row"><h2>{project.name}</h2><span className={project.status === "Live" ? "status live" : "status"}>{project.status}</span></div><p>{project.location}</p><p>{project.industry}</p></div><div className="work-detail"><p className="project-label">{project.work}</p><p>{project.built}</p>{project.url && <a className="text-link" href={project.url} target="_blank" rel="noopener noreferrer">Visit live site</a>}</div></article>; }
export default function Projects() { return <PageIntro className="page-shell inner-page"><header className="page-header"><p className="kicker">Projects</p><h1>Ecommerce & Web Design Projects in Nepal</h1><p className="lede">A selection of client partnerships, freelance projects, and roles that have shaped how I work.</p></header><Script id="project-schema" type="application/ld+json" strategy="beforeInteractive" dangerouslySetInnerHTML={{ __html: JSON.stringify(projectSchema) }} /><section className="work-section"><div className="section-heading"><p className="kicker">Freelance projects</p><h2>Built directly with the business.</h2></div><div className="work-list">{freelanceProjects.map((project) => <ProjectCard project={project} key={project.name} />)}</div></section><section className="work-section work-experience"><div className="section-heading"><p className="kicker">Where I have worked</p><h2>Teams and roles beyond freelance work.</h2></div><div className="work-list">{workExperience.map((project) => <ProjectCard project={project} key={project.name} />)}</div></section><section className="project-contact"><h2>Want to work together?</h2><div><Link className="button button-primary" href="/contact">Start a conversation</Link></div></section><section className="personal-projects"><div className="section-heading"><p className="kicker">Personal projects</p><div><h2>Things I built because I needed them, or just wanted to see if I could.</h2></div></div><div className="personal-project-grid">{personalProjects.map((project) => <article className="personal-project-card" key={project.name}><div><h3>{project.name}</h3><p>{project.description}</p><div className="project-tags">{project.tags.map((tag) => <span key={tag}>{tag}</span>)}</div></div>{project.url ? <a className="button button-primary" href={project.url} target="_blank" rel="noopener noreferrer">View live app</a> : <button className="button button-muted" type="button" disabled>{project.status}</button>}</article>)}</div></section><MoreTeaser /></PageIntro>; }
